name: Reusable GoldenEye

on:
  workflow_call:
    inputs:
      aws-region:
        required: false
        default: eu-west-1
        type: string
      descriptor:
        required: false
        default: 'goldeneye.json'
        type: string
      tag:
        required: false
        default: latest
        type: string
    secrets:
      aws-access-key-id:
        required: false
      aws-secret-access-key:
        required: false
      token:
        required: false
jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
      issues: read
      pull-requests: read
    name: Deploy
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::915473064509:role/GoldenEye-Github
        role-session-name: goldeneye-federation
        aws-region: ${{ inputs.aws-region }}
    - uses: docker://studyportals/goldeneye:be-commit-id2
      with:
        descriptor: ${{ inputs.descriptor }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

