name: Reusable Linting

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        default: "20"
        type: string
      php-version:
        required: false
        default: "7.4"
        type: string
      validate-php-phpmd:
        required: false
        default: false
        type: boolean
    secrets:
      token:
        required: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - id: files
        if: inputs.validate-php-phpmd
        uses: studyportals/get-changed-files@main
        with:
          token: ${{ secrets.token }}
          format: csv
          extensions: ".php"

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - uses: shivammathur/setup-php@v2
        if: inputs.validate-php-phpmd
        with:
          php-version: ${{ inputs.php-version }}

      - run: npm install @studyportals/code-style@$(jq -r '.devDependencies."@studyportals/code-style"' package.json) --no-save --omit=optional
        env:
          CYPRESS_INSTALL_BINARY: 0

      - run: |
          composer config github-oauth.github.com ${{ secrets.token }}
          npm run configure || true
          composer require --dev phpmd/phpmd:$(jq -r '."require-dev"."phpmd/phpmd"' composer.json)
          composer require --dev thecodingmachine/safe --no-interaction --prefer-dist
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        if: inputs.validate-php-phpmd

      - run: |
          if [ -n "${{ steps.files.outputs.added_modified_renamed }}" ]; then
            echo "linting changed files..."

            if [ -f phpmd.baseline.xml ]; then
              echo "Using PHPMD baseline"

              ./vendor/bin/phpmd \
                "${{ steps.files.outputs.added_modified_renamed }}" \
                text \
                phpmd.xml \
                --baseline-file phpmd.baseline.xml
            else
              echo "No PHPMD baseline found"

              ./vendor/bin/phpmd \
                "${{ steps.files.outputs.added_modified_renamed }}" \
                text \
                phpmd.xml
            fi
          fi
        if: inputs.validate-php-phpmd

      - run: cat .github/super-linter.env >> "$GITHUB_ENV"

      - uses: super-linter/super-linter/slim@v6.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          PHP_PHPSTAN_BOOTSTRAP: "./vendor/autoload.php"
